CREATE TABLE goals
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255)   NOT NULL,
    target_amount DECIMAL(15, 2) NOT NULL,
    start_date    DATE           NOT NULL,
    deadline      DATE           NOT NULL,
    user_id       BIGINT         NOT NULL REFERENCES users (id),
    category_id   BIGINT         REFERENCES categories (id)
);
