CREATE TABLE spending_limits
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    limit_amount DECIMAL(15, 2) NOT NULL,
    user_id      BIGINT NOT NULL REFERENCES users (id),
    category_id  BIGINT NOT NULL REFERENCES categories (id),
    UNIQUE (user_id, category_id)
);
